extractor_params = {
    "voxelSetting": {
        "kernelRadius": 2,
        "maskedKernel": True,
        "voxelBatch": 100,
    },
    "setting": {
        "binWidth": 25,
        "label": 1,
        "interpolator": "sitkBSpline",
        "resampledPixelSpacing": None,
        "weightingNorm": None,
    },
    "imageType": {
        "Original": {},
    },
    "featureClass": {
        "firstorder": [
            "Energy",
            "TotalEnergy",
            "Entropy",
            "Minimum",
            "10Percentile",
            "90Percentile",
            "Maximum",
            "Mean",
            "Median",
            "InterquartileRange",
            "Range",
            "MeanAbsoluteDeviation",
            "RobustMeanAbsoluteDeviation",
            "RootMeanSquared",
            "Skewness",
            "Kurtosis",
            "Variance",
            "Uniformity",
        ],
        "glcm": [
            "Autocorrelation",
            "JointAverage",
            "ClusterProminence",
            "ClusterShade",
            "ClusterTendency",
            "Contrast",
            "Correlation",
            "DifferenceAverage",
            "DifferenceEntropy",
            "DifferenceVariance",
            "JointEnergy",
            "JointEntropy",
            "Imc1",
            "Imc2",
            "Idm",
            "MCC",
            "Idmn",
            "Id",
            "Idn",
            "InverseVariance",
            "MaximumProbability",
            #"SumAverage", # When GLCM is symmetrical, μx=μy, and therefore Sum Average=μx+μy=2μx=2∗JointAverage.
            "SumEntropy",
            "SumSquares",
        ],
        "glszm": [
            "SmallAreaEmphasis",
            "LargeAreaEmphasis",
            "GrayLevelNonUniformity",
            "GrayLevelNonUniformityNormalized",
            "SizeZoneNonUniformity",
            "SizeZoneNonUniformityNormalized",
            "ZonePercentage",
            "GrayLevelVariance",
            "ZoneVariance",
            "ZoneEntropy",
            "LowGrayLevelZoneEmphasis",
            "HighGrayLevelZoneEmphasis",
            "SmallAreaLowGrayLevelEmphasis",
            "SmallAreaHighGrayLevelEmphasis",
            "LargeAreaLowGrayLevelEmphasis",
            "LargeAreaHighGrayLevelEmphasis",
        ],
        "glrlm": [
            "ShortRunEmphasis",
            "LongRunEmphasis",
            "GrayLevelNonUniformity",
            "GrayLevelNonUniformityNormalized",
            "RunLengthNonUniformity",
            "RunLengthNonUniformityNormalized",
            "RunPercentage",
            "GrayLevelVariance",
            "RunVariance",
            "RunEntropy",
            "LowGrayLevelRunEmphasis",
            "HighGrayLevelRunEmphasis",
            "ShortRunLowGrayLevelEmphasis",
            "ShortRunHighGrayLevelEmphasis",
            "LongRunLowGrayLevelEmphasis",
            "LongRunHighGrayLevelEmphasis",
        ],
        "ngtdm": [
            "Coarseness",
            "Contrast",
            "Busyness",
            "Complexity",
            "Strength",
        ],
        "gldm": [
            "SmallDependenceEmphasis",
            "LargeDependenceEmphasis",
            "GrayLevelNonUniformity",
            "DependenceNonUniformity",
            "DependenceNonUniformityNormalized",
            "GrayLevelVariance",
            "DependenceVariance",
            "DependenceEntropy",
            "LowGrayLevelEmphasis",
            "HighGrayLevelEmphasis",
            "SmallDependenceLowGrayLevelEmphasis",
            "SmallDependenceHighGrayLevelEmphasis",
            "LargeDependenceLowGrayLevelEmphasis",
            "LargeDependenceHighGrayLevelEmphasis",
        ],
        "shape": [
            "MeshVolume",
            "VoxelVolume",
            "SurfaceArea",
            "SurfaceVolumeRatio",
            "Sphericity",
            "Maximum3DDiameter",
            "Maximum2DDiameterSlice",
            "Maximum2DDiameterColumn",
            "Maximum2DDiameterRow",
            "MajorAxisLength",
            "MinorAxisLength",
            "LeastAxisLength",
            "Elongation",
            "Flatness",
        ],
    },
}