from RecordHandler import RecordHandler

handler = RecordHandler(path='data', out='logs/preprocess.log', clear_log=True, cores=-1)
handler.register()
handler.normalize()
handler.inverseWarp()
handler = RecordHandler(path='data', space='native', out='logs/preprocess.log', clear_log=False, cores=-1)
handler.preprocess()
handler.scaleTargets()
handler.preloadTarget()
handler = RecordHandler(path='data', space='normalized', out='logs/preprocess.log', clear_log=False, cores=-1)
handler.preprocess()
handler.scaleTargets()
handler.preloadTarget()
handler = RecordHandler(path='data', out='logs/preprocess.log', clear_log=False, cores=-1)
handler.preloadCoords()
handler.processClinical()